# Data Manipulation with Pandas

Pandas is a powerful tool for manipulating dataframes, and it can handle tabular data stored in a few frequently used research data formats (e.g. csv, xlsx, txt and even files with no extension). 

For absolute beginners, you can start with [Jake VanderPlas's tutorial](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html). When doing research, you can also rely on the [Pandas official guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html) and [Stack Overflow](https://stackoverflow.com/). You can also find many [cheatsheets](https://www.google.com/search?q=pandas+cheat+sheets&rlz=1C1CHBF_en-GBGB863GB863&oq=pandas+cheat+sheets&aqs=chrome..69i57j0i10i131i433j0i10l8.3750j0j7&sourceid=chrome&ie=UTF-8) and [tricks](https://towardsdatascience.com/30-examples-to-master-pandas-f8a2da751fa4) online. These resources should help you solve most of your problems. This tutorial focuses on processing real world research data in atmospheric sciences using Pandas. 

## Now let's use Pandas to process some air quality data in London
You can get the data from [here](https://github.com/GongdaLu/Gongda-Python-Tutorial-for-Atmospheric-Scientists/tree/main/Data), which was originally downloaded from [DEFRA](https://uk-air.defra.gov.uk/data/data_selector_service?show=auto&submit=Reset&f_limit_was=1). Then you will learn how to work with ".csv" files, manipulate dataframes, conduct some general data anlaysis, handle datetime and make simple plots.

## Part 1: read a single ".csv" file and explore the data

In [1]:
# move to your working directory
import os
os.chdir("move-to-your-working-directory")

# you can check your directory
print("Current directory:",os.getcwd())

Current directory: Y:\Study\Research-Skills\Python\Gongda-Tutorial\Data\London-Air-Quality-Data

In [2]:
# import Pandas
import pandas as pd

# use Pandas to read a single csv file
# skip the first 3 rows as those are texts for data descriptions
# this is not neccesary if the raw data starts from the first row directly
London_AQ_day1 = pd.read_csv("London-AirQualityData-day1.csv",skiprows=3) 

# use "display()" to show the full dataframe
# you can also use "print()", but it is not always good, especially for big dataframes
display(London_AQ_day1)

,Unnamed: 0,Unnamed: 1,London Marylebone Road,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,London N. Kensington,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,London Westminster,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Date,Time,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status
1,2021-01-01,01:00:00,28.53851,V ugm-3,20.99867,V ugm-3,18.6,V ugm-3 (TEOM FDMS),28.53851,V ugm-3,21.65101,V ugm-3,30.448,V ugm-3 (Ref.eq),24.8457,V ugm-3,20,V ugm-3 (BAM)
2,2021-01-01,02:00:00,22.15227,V ugm-3,26.71965,V ugm-3,40.3,V ugm-3 (TEOM FDMS),14.90123,V ugm-3,30.42826,V ugm-3,55.802,V ugm-3 (Ref.eq),20.14728,V ugm-3,26,V ugm-3 (BAM)
3,2021-01-01,03:00:00,31.03314,V ugm-3,21.01699,V ugm-3,23.9,V ugm-3 (TEOM FDMS),31.63185,V ugm-3,19.81852,V ugm-3,28.278,V ugm-3 (Ref.eq),22.26946,V ugm-3,24,V ugm-3 (BAM)
4,2021-01-01,04:00:00,26.04389,V ugm-3,26.59591,V ugm-3,18.1,V ugm-3 (TEOM FDMS),28.98754,V ugm-3,19.37004,V ugm-3,15.613,V ugm-3 (Ref.eq),17.83676,V ugm-3,15,V ugm-3 (BAM)
5,2021-01-01,05:00:00,18.62653,V ugm-3,27.38453,V ugm-3,21.7,V ugm-3 (TEOM FDMS),21.80302,V ugm-3,20.72844,V ugm-3,19.764,V ugm-3 (Ref.eq),26.01874,V ugm-3,21,V ugm-3 (BAM)
6,2021-01-01,06:00:00,17.46238,V ugm-3,23.7544,V ugm-3,22.2,V ugm-3 (TEOM FDMS),26.54281,V ugm-3,16.6376,V ugm-3,17.618,V ugm-3 (Ref.eq),25.50805,V ugm-3,22,V ugm-3 (BAM)
7,2021-01-01,07:00:00,18.56001,V ugm-3,24.15303,V ugm-3,15,V ugm-3 (TEOM FDMS),24.84647,V ugm-3,16.94716,V ugm-3,15.189,V ugm-3 (Ref.eq),27.84591,V ugm-3,18,V ugm-3 (BAM)
8,2021-01-01,08:00:00,15.317,V ugm-3,28.08053,V ugm-3,18.1,V ugm-3 (TEOM FDMS),24.84647,V ugm-3,18.5106,V ugm-3,15.024,V ugm-3 (Ref.eq),32.55692,V ugm-3,15,V ugm-3 (BAM)
9,2021-01-01,09:00:00,15.86582,V ugm-3,29.03062,V ugm-3,18.3,V ugm-3 (TEOM FDMS),23.84862,V ugm-3,20.63106,V ugm-3,15.896,V ugm-3 (Ref.eq),30.16807,V ugm-3,14,V ugm-3 (BAM)
10,2021-01-01,10:00:00,14.10295,V ugm-3,34.71777,V ugm-3,25,V ugm-3 (TEOM FDMS),23.89851,V ugm-3,21.27117,V ugm-3,18.066,V ugm-3 (Ref.eq),31.42084,V ugm-3,21,V ugm-3 (BAM)
11,2021-01-01,11:00:00,15.03427,V ugm-3,36.02664,V ugm-3,24.9,V ugm-3 (TEOM FDMS),25.19571,V ugm-3,18.69776,V ugm-3,20.165,V ugm-3 (Ref.eq),28.35412,V ugm-3,21,V ugm-3 (BAM)
12,2021-01-01,12:00:00,9.44631,V ugm-3,37.11468,V ugm-3,28.6,V ugm-3 (TEOM FDMS),19.80732,V ugm-3,22.11005,V ugm-3,24.481,V ugm-3 (Ref.eq),32.96031,V ugm-3,29,V ugm-3 (BAM)
13,2021-01-01,13:00:00,7.65018,V ugm-3,36.63842,V ugm-3,31.3,V ugm-3 (TEOM FDMS),13.07184,V ugm-3,23.94104,V ugm-3,26.958,V ugm-3 (Ref.eq),34.7287,V ugm-3,29,V ugm-3 (BAM)
14,2021-01-01,14:00:00,4.05792,V ugm-3,40.15931,V ugm-3,32.1,V ugm-3 (TEOM FDMS),7.83312,V ugm-3,29.06284,V ugm-3,28.396,V ugm-3 (Ref.eq),37.68688,V ugm-3,32,V ugm-3 (BAM)
15,2021-01-01,15:00:00,2.46136,V ugm-3,39.55836,V ugm-3,31.1,V ugm-3 (TEOM FDMS),6.98495,V ugm-3,28.87747,V ugm-3,27.948,V ugm-3 (Ref.eq),41.27973,V ugm-3,32,V ugm-3 (BAM)
16,2021-01-01,16:00:00,1.72961,V ugm-3,38.07461,V ugm-3,28.8,V ugm-3 (TEOM FDMS),3.44258,V ugm-3,32.1794,V ugm-3,24.505,V ugm-3 (Ref.eq),44.24978,V ugm-3,36,V ugm-3 (BAM)
17,2021-01-01,17:00:00,1.39699,V ugm-3,43.94627,V ugm-3,28.3,V ugm-3 (TEOM FDMS),3.79183,V ugm-3,34.718,V ugm-3,21.439,V ugm-3 (Ref.eq),45.96508,V ugm-3,38,V ugm-3 (BAM)
18,2021-01-01,18:00:00,1.49678,V ugm-3,41.71404,V ugm-3,23.4,V ugm-3 (TEOM FDMS),2.34495,V ugm-3,36.70487,V ugm-3,20.401,V ugm-3 (Ref.eq),46.83039,V ugm-3,34,V ugm-3 (BAM)
19,2021-01-01,19:00:00,1.33047,V ugm-3,39.32475,V ugm-3,21.9,V ugm-3 (TEOM FDMS),3.54237,V ugm-3,36.05357,V ugm-3,20.047,V ugm-3 (Ref.eq),47.44059,V ugm-3,24,V ugm-3 (BAM)
20,2021-01-01,20:00:00,3.19312,V ugm-3,33.29582,V ugm-3,15.3,V ugm-3 (TEOM FDMS),4.19097,V ugm-3,35.44433,V ugm-3,19.976,V ugm-3 (Ref.eq),45.59587,V ugm-3,18,V ugm-3 (BAM)
21,2021-01-01,21:00:00,12.90553,V ugm-3,25.81454,V ugm-3,11.3,V ugm-3 (TEOM FDMS),14.96775,V ugm-3,28.4701,V ugm-3,14.34,V ugm-3 (Ref.eq),35.68105,V ugm-3,13,V ugm-3 (BAM)
22,2021-01-01,22:00:00,21.0879,V ugm-3,16.02034,V ugm-3,8.8,V ugm-3 (TEOM FDMS),25.69464,V ugm-3,19.15205,V ugm-3,9.057,V ugm-3 (Ref.eq),26.01861,V ugm-3,11,V ugm-3 (BAM)
23,2021-01-01,23:00:00,25.74453,V ugm-3,11.99551,V ugm-3,8,V ugm-3 (TEOM FDMS),28.53851,V ugm-3,16.63179,V ugm-3,8.585,V ugm-3 (Ref.eq),21.81495,V ugm-3,8,V ugm-3 (BAM)
24,2021-01-01,24:00:00,24.8132,V ugm-3,15.24703,V ugm-3,7,V ugm-3 (TEOM FDMS),30.08518,V ugm-3,14.46666,V ugm-3,8.443,V ugm-3 (Ref.eq),20.33734,V ugm-3,10,V ugm-3 (BAM)
25,End,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# show the first five rows of the dataframe
display(London_AQ_day1.head())

,Unnamed: 0,Unnamed: 1,London Marylebone Road,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,London N. Kensington,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,London Westminster,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Date,Time,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status
1,2021-01-01,01:00:00,28.53851,V ugm-3,20.99867,V ugm-3,18.6,V ugm-3 (TEOM FDMS),28.53851,V ugm-3,21.65101,V ugm-3,30.448,V ugm-3 (Ref.eq),24.8457,V ugm-3,20,V ugm-3 (BAM)
2,2021-01-01,02:00:00,22.15227,V ugm-3,26.71965,V ugm-3,40.3,V ugm-3 (TEOM FDMS),14.90123,V ugm-3,30.42826,V ugm-3,55.802,V ugm-3 (Ref.eq),20.14728,V ugm-3,26,V ugm-3 (BAM)
3,2021-01-01,03:00:00,31.03314,V ugm-3,21.01699,V ugm-3,23.9,V ugm-3 (TEOM FDMS),31.63185,V ugm-3,19.81852,V ugm-3,28.278,V ugm-3 (Ref.eq),22.26946,V ugm-3,24,V ugm-3 (BAM)
4,2021-01-01,04:00:00,26.04389,V ugm-3,26.59591,V ugm-3,18.1,V ugm-3 (TEOM FDMS),28.98754,V ugm-3,19.37004,V ugm-3,15.613,V ugm-3 (Ref.eq),17.83676,V ugm-3,15,V ugm-3 (BAM)

In [4]:
# show the last five rows of the dataframe
display(London_AQ_day1.tail())

,Unnamed: 0,Unnamed: 1,London Marylebone Road,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,London N. Kensington,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,London Westminster,Unnamed: 15,Unnamed: 16,Unnamed: 17
21,2021-01-01,21:00:00,12.90553,V ugm-3,25.81454,V ugm-3,11.3,V ugm-3 (TEOM FDMS),14.96775,V ugm-3,28.4701,V ugm-3,14.34,V ugm-3 (Ref.eq),35.68105,V ugm-3,13,V ugm-3 (BAM)
22,2021-01-01,22:00:00,21.0879,V ugm-3,16.02034,V ugm-3,8.8,V ugm-3 (TEOM FDMS),25.69464,V ugm-3,19.15205,V ugm-3,9.057,V ugm-3 (Ref.eq),26.01861,V ugm-3,11,V ugm-3 (BAM)
23,2021-01-01,23:00:00,25.74453,V ugm-3,11.99551,V ugm-3,8,V ugm-3 (TEOM FDMS),28.53851,V ugm-3,16.63179,V ugm-3,8.585,V ugm-3 (Ref.eq),21.81495,V ugm-3,8,V ugm-3 (BAM)
24,2021-01-01,24:00:00,24.8132,V ugm-3,15.24703,V ugm-3,7,V ugm-3 (TEOM FDMS),30.08518,V ugm-3,14.46666,V ugm-3,8.443,V ugm-3 (Ref.eq),20.33734,V ugm-3,10,V ugm-3 (BAM)
25,End,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# understand the dimensions of the dataframe
print("dataframe shape:",London_AQ_day1.shape)
print("number of rows:",London_AQ_day1.shape[0])
print("number of columns:",London_AQ_day1.shape[1])

dataframe shape: (26, 18)
number of rows: 26
number of columns: 18

In [6]:
# get a subset of dataframe using index
# let's get the first 8 columns and remove the last row, which is not the actual data

# the syntax is: df.iloc[rows,columns]
# but there are multiple ways to achive it

# you can try
Mary_AQ_day1 = London_AQ_day1.iloc[0:25,0:8]

# or
Mary_AQ_day1 = London_AQ_day1.iloc[0:London_AQ_day1.shape[0]-1,0:8]

# or
Mary_AQ_day1 = London_AQ_day1.iloc[0:-1,0:8]

# check results
display(Mary_AQ_day1)

,Unnamed: 0,Unnamed: 1,London Marylebone Road,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Date,Time,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status
1,2021-01-01,01:00:00,28.53851,V ugm-3,20.99867,V ugm-3,18.6,V ugm-3 (TEOM FDMS)
2,2021-01-01,02:00:00,22.15227,V ugm-3,26.71965,V ugm-3,40.3,V ugm-3 (TEOM FDMS)
3,2021-01-01,03:00:00,31.03314,V ugm-3,21.01699,V ugm-3,23.9,V ugm-3 (TEOM FDMS)
4,2021-01-01,04:00:00,26.04389,V ugm-3,26.59591,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
5,2021-01-01,05:00:00,18.62653,V ugm-3,27.38453,V ugm-3,21.7,V ugm-3 (TEOM FDMS)
6,2021-01-01,06:00:00,17.46238,V ugm-3,23.7544,V ugm-3,22.2,V ugm-3 (TEOM FDMS)
7,2021-01-01,07:00:00,18.56001,V ugm-3,24.15303,V ugm-3,15,V ugm-3 (TEOM FDMS)
8,2021-01-01,08:00:00,15.317,V ugm-3,28.08053,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
9,2021-01-01,09:00:00,15.86582,V ugm-3,29.03062,V ugm-3,18.3,V ugm-3 (TEOM FDMS)
10,2021-01-01,10:00:00,14.10295,V ugm-3,34.71777,V ugm-3,25,V ugm-3 (TEOM FDMS)
11,2021-01-01,11:00:00,15.03427,V ugm-3,36.02664,V ugm-3,24.9,V ugm-3 (TEOM FDMS)
12,2021-01-01,12:00:00,9.44631,V ugm-3,37.11468,V ugm-3,28.6,V ugm-3 (TEOM FDMS)
13,2021-01-01,13:00:00,7.65018,V ugm-3,36.63842,V ugm-3,31.3,V ugm-3 (TEOM FDMS)
14,2021-01-01,14:00:00,4.05792,V ugm-3,40.15931,V ugm-3,32.1,V ugm-3 (TEOM FDMS)
15,2021-01-01,15:00:00,2.46136,V ugm-3,39.55836,V ugm-3,31.1,V ugm-3 (TEOM FDMS)
16,2021-01-01,16:00:00,1.72961,V ugm-3,38.07461,V ugm-3,28.8,V ugm-3 (TEOM FDMS)
17,2021-01-01,17:00:00,1.39699,V ugm-3,43.94627,V ugm-3,28.3,V ugm-3 (TEOM FDMS)
18,2021-01-01,18:00:00,1.49678,V ugm-3,41.71404,V ugm-3,23.4,V ugm-3 (TEOM FDMS)
19,2021-01-01,19:00:00,1.33047,V ugm-3,39.32475,V ugm-3,21.9,V ugm-3 (TEOM FDMS)
20,2021-01-01,20:00:00,3.19312,V ugm-3,33.29582,V ugm-3,15.3,V ugm-3 (TEOM FDMS)
21,2021-01-01,21:00:00,12.90553,V ugm-3,25.81454,V ugm-3,11.3,V ugm-3 (TEOM FDMS)
22,2021-01-01,22:00:00,21.0879,V ugm-3,16.02034,V ugm-3,8.8,V ugm-3 (TEOM FDMS)
23,2021-01-01,23:00:00,25.74453,V ugm-3,11.99551,V ugm-3,8,V ugm-3 (TEOM FDMS)
24,2021-01-01,24:00:00,24.8132,V ugm-3,15.24703,V ugm-3,7,V ugm-3 (TEOM FDMS)

In [7]:
# assign column names based on values in the first row
Mary_AQ_day1.columns = Mary_AQ_day1.iloc[0,:]

# then remove the current first row as it is not needed anymore
Mary_AQ_day1 = Mary_AQ_day1.drop(0)

# reset the index for each row
Mary_AQ_day1 = Mary_AQ_day1.reset_index(drop=True)

# show the result
display(Mary_AQ_day1)

,Date,Time,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status
0,2021-01-01,01:00:00,28.53851,V ugm-3,20.99867,V ugm-3,18.6,V ugm-3 (TEOM FDMS)
1,2021-01-01,02:00:00,22.15227,V ugm-3,26.71965,V ugm-3,40.3,V ugm-3 (TEOM FDMS)
2,2021-01-01,03:00:00,31.03314,V ugm-3,21.01699,V ugm-3,23.9,V ugm-3 (TEOM FDMS)
3,2021-01-01,04:00:00,26.04389,V ugm-3,26.59591,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
4,2021-01-01,05:00:00,18.62653,V ugm-3,27.38453,V ugm-3,21.7,V ugm-3 (TEOM FDMS)
5,2021-01-01,06:00:00,17.46238,V ugm-3,23.7544,V ugm-3,22.2,V ugm-3 (TEOM FDMS)
6,2021-01-01,07:00:00,18.56001,V ugm-3,24.15303,V ugm-3,15,V ugm-3 (TEOM FDMS)
7,2021-01-01,08:00:00,15.317,V ugm-3,28.08053,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
8,2021-01-01,09:00:00,15.86582,V ugm-3,29.03062,V ugm-3,18.3,V ugm-3 (TEOM FDMS)
9,2021-01-01,10:00:00,14.10295,V ugm-3,34.71777,V ugm-3,25,V ugm-3 (TEOM FDMS)
10,2021-01-01,11:00:00,15.03427,V ugm-3,36.02664,V ugm-3,24.9,V ugm-3 (TEOM FDMS)
11,2021-01-01,12:00:00,9.44631,V ugm-3,37.11468,V ugm-3,28.6,V ugm-3 (TEOM FDMS)
12,2021-01-01,13:00:00,7.65018,V ugm-3,36.63842,V ugm-3,31.3,V ugm-3 (TEOM FDMS)
13,2021-01-01,14:00:00,4.05792,V ugm-3,40.15931,V ugm-3,32.1,V ugm-3 (TEOM FDMS)
14,2021-01-01,15:00:00,2.46136,V ugm-3,39.55836,V ugm-3,31.1,V ugm-3 (TEOM FDMS)
15,2021-01-01,16:00:00,1.72961,V ugm-3,38.07461,V ugm-3,28.8,V ugm-3 (TEOM FDMS)
16,2021-01-01,17:00:00,1.39699,V ugm-3,43.94627,V ugm-3,28.3,V ugm-3 (TEOM FDMS)
17,2021-01-01,18:00:00,1.49678,V ugm-3,41.71404,V ugm-3,23.4,V ugm-3 (TEOM FDMS)
18,2021-01-01,19:00:00,1.33047,V ugm-3,39.32475,V ugm-3,21.9,V ugm-3 (TEOM FDMS)
19,2021-01-01,20:00:00,3.19312,V ugm-3,33.29582,V ugm-3,15.3,V ugm-3 (TEOM FDMS)
20,2021-01-01,21:00:00,12.90553,V ugm-3,25.81454,V ugm-3,11.3,V ugm-3 (TEOM FDMS)
21,2021-01-01,22:00:00,21.0879,V ugm-3,16.02034,V ugm-3,8.8,V ugm-3 (TEOM FDMS)
22,2021-01-01,23:00:00,25.74453,V ugm-3,11.99551,V ugm-3,8,V ugm-3 (TEOM FDMS)
23,2021-01-01,24:00:00,24.8132,V ugm-3,15.24703,V ugm-3,7,V ugm-3 (TEOM FDMS)

In [8]:
# make a copy of this dataframe, so you can always come back at this step
Mary_AQ_day1_copy = Mary_AQ_day1.copy()
display(Mary_AQ_day1_copy)

,Date,Time,Ozone,Status,Nitrogen dioxide,Status,PM2.5 particulate matter (Hourly measured),Status
0,2021-01-01,01:00:00,28.53851,V ugm-3,20.99867,V ugm-3,18.6,V ugm-3 (TEOM FDMS)
1,2021-01-01,02:00:00,22.15227,V ugm-3,26.71965,V ugm-3,40.3,V ugm-3 (TEOM FDMS)
2,2021-01-01,03:00:00,31.03314,V ugm-3,21.01699,V ugm-3,23.9,V ugm-3 (TEOM FDMS)
3,2021-01-01,04:00:00,26.04389,V ugm-3,26.59591,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
4,2021-01-01,05:00:00,18.62653,V ugm-3,27.38453,V ugm-3,21.7,V ugm-3 (TEOM FDMS)
5,2021-01-01,06:00:00,17.46238,V ugm-3,23.7544,V ugm-3,22.2,V ugm-3 (TEOM FDMS)
6,2021-01-01,07:00:00,18.56001,V ugm-3,24.15303,V ugm-3,15,V ugm-3 (TEOM FDMS)
7,2021-01-01,08:00:00,15.317,V ugm-3,28.08053,V ugm-3,18.1,V ugm-3 (TEOM FDMS)
8,2021-01-01,09:00:00,15.86582,V ugm-3,29.03062,V ugm-3,18.3,V ugm-3 (TEOM FDMS)
9,2021-01-01,10:00:00,14.10295,V ugm-3,34.71777,V ugm-3,25,V ugm-3 (TEOM FDMS)
10,2021-01-01,11:00:00,15.03427,V ugm-3,36.02664,V ugm-3,24.9,V ugm-3 (TEOM FDMS)
11,2021-01-01,12:00:00,9.44631,V ugm-3,37.11468,V ugm-3,28.6,V ugm-3 (TEOM FDMS)
12,2021-01-01,13:00:00,7.65018,V ugm-3,36.63842,V ugm-3,31.3,V ugm-3 (TEOM FDMS)
13,2021-01-01,14:00:00,4.05792,V ugm-3,40.15931,V ugm-3,32.1,V ugm-3 (TEOM FDMS)
14,2021-01-01,15:00:00,2.46136,V ugm-3,39.55836,V ugm-3,31.1,V ugm-3 (TEOM FDMS)
15,2021-01-01,16:00:00,1.72961,V ugm-3,38.07461,V ugm-3,28.8,V ugm-3 (TEOM FDMS)
16,2021-01-01,17:00:00,1.39699,V ugm-3,43.94627,V ugm-3,28.3,V ugm-3 (TEOM FDMS)
17,2021-01-01,18:00:00,1.49678,V ugm-3,41.71404,V ugm-3,23.4,V ugm-3 (TEOM FDMS)
18,2021-01-01,19:00:00,1.33047,V ugm-3,39.32475,V ugm-3,21.9,V ugm-3 (TEOM FDMS)
19,2021-01-01,20:00:00,3.19312,V ugm-3,33.29582,V ugm-3,15.3,V ugm-3 (TEOM FDMS)
20,2021-01-01,21:00:00,12.90553,V ugm-3,25.81454,V ugm-3,11.3,V ugm-3 (TEOM FDMS)
21,2021-01-01,22:00:00,21.0879,V ugm-3,16.02034,V ugm-3,8.8,V ugm-3 (TEOM FDMS)
22,2021-01-01,23:00:00,25.74453,V ugm-3,11.99551,V ugm-3,8,V ugm-3 (TEOM FDMS)
23,2021-01-01,24:00:00,24.8132,V ugm-3,15.24703,V ugm-3,7,V ugm-3 (TEOM FDMS)

In [9]:
# check column names
print("all column names:",Mary_AQ_day1.columns.values,sep="\n")

all column names:
['Date' 'Time' 'Ozone' 'Status' 'Nitrogen dioxide' 'Status'
 'PM2.5 particulate matter (Hourly measured)' 'Status']

In [10]:
# select columns by column names

# a single column
display(Mary_AQ_day1.Date)

# a single column
display(Mary_AQ_day1['Date'])

# a few columns
display(Mary_AQ_day1[['Date','Time','Ozone']])

# a few columns
Date_columns = ['Date','Time']
Species_columns = ['Ozone','Nitrogen dioxide']
display(Mary_AQ_day1[Date_columns+Species_columns])

0     2021-01-01
1     2021-01-01
2     2021-01-01
3     2021-01-01
4     2021-01-01
5     2021-01-01
6     2021-01-01
7     2021-01-01
8     2021-01-01
9     2021-01-01
10    2021-01-01
11    2021-01-01
12    2021-01-01
13    2021-01-01
14    2021-01-01
15    2021-01-01
16    2021-01-01
17    2021-01-01
18    2021-01-01
19    2021-01-01
20    2021-01-01
21    2021-01-01
22    2021-01-01
23    2021-01-01
Name: Date, dtype: object

0     2021-01-01
1     2021-01-01
2     2021-01-01
3     2021-01-01
4     2021-01-01
5     2021-01-01
6     2021-01-01
7     2021-01-01
8     2021-01-01
9     2021-01-01
10    2021-01-01
11    2021-01-01
12    2021-01-01
13    2021-01-01
14    2021-01-01
15    2021-01-01
16    2021-01-01
17    2021-01-01
18    2021-01-01
19    2021-01-01
20    2021-01-01
21    2021-01-01
22    2021-01-01
23    2021-01-01
Name: Date, dtype: object

0         Date      Time     Ozone
0   2021-01-01  01:00:00  28.53851
1   2021-01-01  02:00:00  22.15227
2   2021-01-01  03:00:00  31.03314
3   2021-01-01  04:00:00  26.04389
4   2021-01-01  05:00:00  18.62653
5   2021-01-01  06:00:00  17.46238
6   2021-01-01  07:00:00  18.56001
7   2021-01-01  08:00:00    15.317
8   2021-01-01  09:00:00  15.86582
9   2021-01-01  10:00:00  14.10295
10  2021-01-01  11:00:00  15.03427
11  2021-01-01  12:00:00   9.44631
12  2021-01-01  13:00:00   7.65018
13  2021-01-01  14:00:00   4.05792
14  2021-01-01  15:00:00   2.46136
15  2021-01-01  16:00:00   1.72961
16  2021-01-01  17:00:00   1.39699
17  2021-01-01  18:00:00   1.49678
18  2021-01-01  19:00:00   1.33047
19  2021-01-01  20:00:00   3.19312
20  2021-01-01  21:00:00  12.90553
21  2021-01-01  22:00:00   21.0879
22  2021-01-01  23:00:00  25.74453
23  2021-01-01  24:00:00   24.8132

0         Date      Time     Ozone Nitrogen dioxide
0   2021-01-01  01:00:00  28.53851         20.99867
1   2021-01-01  02:00:00  22.15227         26.71965
2   2021-01-01  03:00:00  31.03314         21.01699
3   2021-01-01  04:00:00  26.04389         26.59591
4   2021-01-01  05:00:00  18.62653         27.38453
5   2021-01-01  06:00:00  17.46238          23.7544
6   2021-01-01  07:00:00  18.56001         24.15303
7   2021-01-01  08:00:00    15.317         28.08053
8   2021-01-01  09:00:00  15.86582         29.03062
9   2021-01-01  10:00:00  14.10295         34.71777
10  2021-01-01  11:00:00  15.03427         36.02664
11  2021-01-01  12:00:00   9.44631         37.11468
12  2021-01-01  13:00:00   7.65018         36.63842
13  2021-01-01  14:00:00   4.05792         40.15931
14  2021-01-01  15:00:00   2.46136         39.55836
15  2021-01-01  16:00:00   1.72961         38.07461
16  2021-01-01  17:00:00   1.39699         43.94627
17  2021-01-01  18:00:00   1.49678         41.71404
18  2021-01-01  19:00:00   1.33047         39.32475
19  2021-01-01  20:00:00   3.19312         33.29582
20  2021-01-01  21:00:00  12.90553         25.81454
21  2021-01-01  22:00:00   21.0879         16.02034
22  2021-01-01  23:00:00  25.74453         11.99551
23  2021-01-01  24:00:00   24.8132         15.24703

## Part 2: read multiple ".csv" files and manipulate the data

In [12]:
# list the csv files in this directory
import glob

London_files = glob.glob('London*.csv')
display(London_files)

['London-AirQualityData-day1.csv',
 'London-AirQualityData-day2.csv',
 'London-AirQualityData-day3.csv',
 'London-AirQualityData-week1.csv']

In [13]:
# sort the files by name (although here files were already sorted by default)
London_files = sorted(London_files)
display(London_files)

['London-AirQualityData-day1.csv',
 'London-AirQualityData-day2.csv',
 'London-AirQualityData-day3.csv',
 'London-AirQualityData-week1.csv']

In [12]:
# or you can list the sorted files directly (although here files were already sorted by default)
London_files = sorted(glob.glob('London*.csv'))
display(London_files)

['LondonAirQualityDataHourly-Day1.csv',
 'LondonAirQualityDataHourly-Day2.csv',
 'LondonAirQualityDataHourly-Day3.csv',
 'LondonAirQualityDataHourly-Month.csv']

In [14]:
# only select daily files
London_files_daily = sorted(glob.glob('London*Day*.csv'))
display(London_files_daily )

['London-AirQualityData-day1.csv',
 'London-AirQualityData-day2.csv',
 'London-AirQualityData-day3.csv']

## Part 3: read tabular data stored in other file formats

## Part 4: save out the results

## Part 5: data visualisations using Pandas

### Pandas dataframes can also be converted from or to N-dimensional arrays which are normally stored in [netCDF files](https://www.unidata.ucar.edu/software/netcdf/). This will be introduced after.